In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [38]:
# change the datasest and the sheet accordding to the requirement and the saved name 

final_data = pd.read_excel("Final Data File_Validation.xlsx",sheet_name='Data Set with Values') 
final_data.drop("Unnamed: 35", axis = 1, inplace = True)

In [39]:
proper_column_names =['Unique ID','Start Date', 'End Date', 'Age', 'Gender', 'Urban/Rural', 'Income', 'Beer', 'Flavored/Mixed Beer','Non-Alcoholic Beers', 'Hard Ciders','Hard Kombucha', 'Wine', 'Hard Beverage', 'Distilled Spirits','Domestic Light Beer', 'Domestic Regular Beer','Low Calorie Carb Beer', 'Domestic Craft', 'Imported Mexican Beer', 'Other Imported Beer', 'Non-Alcoholic Beer','Concept Relevance','Concept Appeal','Concept Differentiation','Concept Beleivability','Concept_Price','Concept_Purchase Intent','Concept_Drinking Frequency','What is the most important thing you LIKE about the shown concept?','What is the most important thing you DISLIKE about the shown concept?','Concept_Replacement Product','Q18A','Q18B','Q18C']

In [40]:
data_gpt = pd.read_excel("Final Data File_Test.xlsx",sheet_name='Data Set with Labels Text')
data_gpt.columns = proper_column_names
data_gpt.drop(0, inplace = True)

missing_list=[]

for col in data_gpt.columns:
    if data_gpt[col].isna().sum() > 0:
        print(col)
        missing_list.append(col)


data_gpt[missing_list] = data_gpt[missing_list].fillna("no response")

What is the most important thing you LIKE about the shown concept?
What is the most important thing you DISLIKE about the shown concept?
Q18A
Q18B
Q18C

In [41]:
test_df = final_data.copy()
test_df.columns = proper_column_names

In [42]:
test_df.drop(0, inplace = True)

In [43]:
test_df['Start Date'] = pd.to_datetime(test_df['Start Date'], format="%d-%m-%Y %H:%M")
test_df['End Date'] = pd.to_datetime(test_df['End Date'], format="%d-%m-%Y %H:%M")

# Compute response time (in minutes)
test_df['response_time_minutes'] = (test_df['End Date'] - test_df['Start Date']).dt.total_seconds() / 60

In [44]:
num_cat = ['Beer', 'Flavored/Mixed Beer','Non-Alcoholic Beers', 'Hard Ciders','Hard Kombucha', 'Wine', 'Hard Beverage', 'Distilled Spirits','Domestic Light Beer', 'Domestic Regular Beer','Low Calorie Carb Beer', 'Low Calorie Carb Beer', 'Domestic Craft', 'Imported Mexican Beer', 'Other Imported Beer', 'Non-Alcoholic Beer']
categorical_features = ['Urban/Rural','Concept_Replacement Product']

In [45]:
df = test_df.copy()
for col in num_cat:
    df[col] = pd.to_numeric(df[col],errors='coerce')

df_transformed = pd.get_dummies(df, columns=categorical_features,dtype=float)
df_transformed

,Unique ID,Start Date,End Date,Age,Gender,Income,Beer,Flavored/Mixed Beer,Non-Alcoholic Beers,Hard Ciders,...,Q18C,response_time_minutes,Urban/Rural_1.0,Urban/Rural_2.0,Urban/Rural_3.0,Urban/Rural_4.0,Urban/Rural_5.0,Concept_Replacement Product_1.0,Concept_Replacement Product_2.0,Concept_Replacement Product_3.0
1,4.0,2024-10-11 09:40:35,2024-10-11 09:54:15,34.0,2.0,6.0,1,0,0,1,...,NaN,13.666667,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,25.0,2024-10-11 10:11:38,2024-10-11 10:30:35,54.0,1.0,12.0,1,1,0,1,...,miller life,18.950000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,27.0,2024-10-11 10:15:56,2024-10-11 10:33:13,64.0,2.0,11.0,1,0,0,0,...,Coca Cola,17.283333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,33.0,2024-10-11 11:02:14,2024-10-11 11:37:29,44.0,1.0,12.0,1,0,0,0,...,Costco,35.250000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,38.0,2024-10-11 15:17:49,2024-10-11 15:42:31,55.0,1.0,3.0,1,0,0,0,...,NaN,24.700000,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,3149.0,2024-10-24 14:41:53,2024-10-24 14:52:40,39.0,2.0,4.0,1,1,0,1,...,NaN,10.783333,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
405,3153.0,2024-10-24 14:36:41,2024-10-24 14:56:33,46.0,2.0,1.0,1,0,0,0,...,Coors,19.866667,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
406,3154.0,2024-10-24 14:50:54,2024-10-24 14:59:52,55.0,1.0,4.0,1,0,0,0,...,NaN,8.966667,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
407,3155.0,2024-10-24 14:18:19,2024-10-24 15:03:10,56.0,2.0,4.0,1,1,0,0,...,Michelob,44.850000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
408,3213.0,2024-10-24 17:22:51,2024-10-24 17:33:55,56.0,2.0,1.0,1,0,0,0,...,NaN,11.066667,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [46]:
df_transformed["Q18"] = df_transformed["Q18A"]+ " "+ df_transformed["Q18B"]+" " + df_transformed["Q18C"]
df_transformed.drop(["Q18A","Q18B","Q18C"], axis = 1, inplace  = True)

In [47]:
missing_list=[]

for col in df_transformed.columns:
    if df_transformed[col].isna().sum() > 0:
        print(col)
        missing_list.append(col)


df_transformed[missing_list] = df_transformed[missing_list].fillna("no response")

What is the most important thing you LIKE about the shown concept?
What is the most important thing you DISLIKE about the shown concept?
Q18

In [48]:
import re
import spacy

nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    if pd.isna(text):  # Handle NaN
        return "No Response"
    
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\s+', ' ', text)  # Remove extra spaces
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    
    # Lemmatization using spaCy
    doc = nlp(text)
    text = " ".join([token.lemma_ for token in doc if not token.is_stop])  # Remove stopwords and lemmatize
    
    return text

In [49]:
text_col = missing_list
for col in text_col:
    df_transformed[col] = df_transformed[col].apply(clean_text)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

vectorizers = {}
bow_features = []

# Ensure text columns do not have missing values

for col in text_col:
    vectorizer = CountVectorizer(max_features=3)  # Adjust max_features as needed
    bow_matrix = vectorizer.fit_transform(df_transformed[col])

    vectorizers[col] = vectorizer  # Store vectorizer for later use (optional)

    # Convert BoW matrix to DataFrame
    bow_df = pd.DataFrame(bow_matrix.toarray(), 
                          columns=[f"{col}_{word}" for word in vectorizer.get_feature_names_out()])

    # Reset index to avoid merging issues
    bow_df.reset_index(drop=True, inplace=True)
    
    bow_features.append(bow_df)

# Merge all BoW features into a single DataFrame
bow_df_final = pd.concat(bow_features, axis=1)

# Reset index before merging to avoid shape mismatches
df_transformed.reset_index(drop=True, inplace=True)
bow_df_final.reset_index(drop=True, inplace=True)

# Combine with original DataFrame (excluding text columns)
df_bow = pd.concat([df_transformed.drop(columns=text_col), bow_df_final], axis=1)

# Display final DataFrame shape
print(df_bow.shape)

(408, 46)

In [51]:
X = df_bow.copy()

X.drop(["Start Date","End Date"], axis =1, inplace = True)

In [52]:
import pickle

# Load the saved model
with open("best_xgb_model2_ed_final.pkl", "rb") as f:
    loaded_model = pickle.load(f)

# Now you can use loaded_model to make predictions

In [53]:
y_submission = loaded_model.predict(X.to_numpy())

In [54]:
from collections import Counter

print(Counter(y_submission))

Counter({0: 340, 1: 68})

In [55]:
prob_arr = loaded_model.predict_proba(X.to_numpy())
unsure_indices = np.where(((prob_arr[:, 0] > 0.40) & (prob_arr[:, 0] < 0.6)) | 
                          ((prob_arr[:, 1] > 0.40) & (prob_arr[:, 1] < 0.6)))
unsure_indices[0]

array([  0,   1,   3,   5,   6,   8,  10,  13,  14,  15,  18,  19,  24,
        26,  28,  29,  30,  31,  33,  35,  37,  39,  40,  45,  47,  53,
        59,  60,  62,  63,  65,  68,  70,  71,  73,  74,  76,  78,  79,
        82,  84,  86,  95, 101, 115, 121, 124, 125, 126, 200, 202, 204,
       206, 207, 209, 210, 216, 217, 219, 220, 221, 222, 223, 224, 226,
       228, 230, 231, 232, 233, 235, 236, 241, 242, 250, 257, 258, 263,
       266, 268, 269, 275, 276, 278, 280, 283, 291, 292, 295, 298, 299,
       300, 303, 305, 309, 310, 311, 315, 316, 321, 323, 324, 329, 330,
       331, 332, 335, 337, 339, 340, 343, 346, 348, 349, 352, 355, 360,
       361, 362, 363, 364, 365, 368, 369, 370, 372, 373, 375, 376, 402],
      dtype=int64)

In [56]:
data_gpt = data_gpt.iloc[unsure_indices[0]]
data_gpt

,Unique ID,Start Date,End Date,Age,Gender,Urban/Rural,Income,Beer,Flavored/Mixed Beer,Non-Alcoholic Beers,...,Concept Beleivability,Concept_Price,Concept_Purchase Intent,Concept_Drinking Frequency,What is the most important thing you LIKE about the shown concept?,What is the most important thing you DISLIKE about the shown concept?,Concept_Replacement Product,Q18A,Q18B,Q18C
1,7.0,2024-10-11 09:47:52,2024-10-11 09:56:52,65.0,Male,Rural / distant or remote,"Less than $20,000",Yes,No,No,...,Somewhat Believable,About Average,Definitely Would Not Buy,Never,Nothing,It is a light beer,Be used in addition to products you are curren...,no response,no response,no response
2,15.0,2024-10-11 09:49:42,2024-10-11 10:10:49,63.0,Female,Rural / distant or remote,"$20,000 to $29,999",Yes,No,No,...,Very Believable,Somewhat Expensive,Probably Would Buy,Once Every 2 to 3 Weeks,Only 70 calories,Price,Totally replace products you are currently dri...,Michelob Ultra,Bud light,Michelob
4,28.0,2024-10-11 10:11:36,2024-10-11 10:39:16,45.0,Male,Suburban / just outside of a city,"$100,000 to $149,999",Yes,No,No,...,Somewhat Believable,Somewhat Expensive,May or May Not Buy,Once Every 2 to 3 Weeks,refreshing,cost,Sometimes replace products you are currently d...,millter,coors,bud
6,41.0,2024-10-11 18:15:49,2024-10-11 18:23:18,36.0,Male,Suburban / just outside of a city,"$40,000 to $49,999",Yes,Yes,Yes,...,Very Believable,Very Expensive,Definitely Would Buy,Daily/Nightly,I like the experience,Nothing it's good,Totally replace products you are currently dri...,Bud light,Coors,Corons
7,46.0,2024-10-11 22:48:57,2024-10-11 23:15:13,59.0,Female,Big city,"$20,000 to $29,999",Yes,No,No,...,Very Believable,About Average,Definitely Would Not Buy,Never,There isn't anything I like about a beer that ...,I don't like that it's a certified organic lig...,Be used in addition to products you are curren...,no response,no response,no response
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,2812.0,2024-10-24 12:50:38,2024-10-24 13:01:38,52.0,Male,Big city,"$70,000 to $79,999",Yes,No,No,...,Very Believable,About Average,May or May Not Buy,Once a Week,Low calorie,Not a big fan of Michelob,Sometimes replace products you are currently d...,Yeungling,Bud Light,Coors Light
374,2820.0,2024-10-24 12:53:05,2024-10-24 13:06:07,54.0,Male,Suburban / just outside of a city,"$20,000 to $29,999",Yes,No,No,...,Very Believable,About Average,Definitely Would Buy,Two or Three Days/Nights a Week,The alcohol content is good.,There's nothing I dislike.,Totally replace products you are currently dri...,Budweiser,Miller,Coors
376,2829.0,2024-10-24 12:32:33,2024-10-24 13:10:00,50.0,Female,Small city,"$20,000 to $29,999",Yes,No,No,...,Very Believable,About Average,Probably Would Not Buy,Less Often Than Every 6 Months,I like that it only has 70 calories and 2.3 ca...,I dislike that it’s a lower abv drink. When I ...,Be used in addition to products you are curren...,no response,no response,no response
377,2830.0,2024-10-24 12:59:23,2024-10-24 13:10:06,57.0,Female,Suburban / just outside of a city,"Less than $20,000",Yes,No,No,...,Very Believable,About Average,Probably Would Buy,Once a Week,It's made by michelob,No dislikes,Be used in addition to products you are curren...,no response,no response,no response
403,2978.0,2024-10-24 13:41:01,2024-10-24 13:55:49,55.0,Male,Big city,"$30,000 to $39,999",Yes,Yes,No,...,Very Believable,About Average,Probably Would Buy,Two or Three Days/Nights a Week,The Michelle brand itself,no response,Be used in addition to products you are curren...,no response,no response,no response

In [57]:
import google.generativeai as genai
# Set up API key
genai.configure(api_key="AIzaSyA2FLkqwfhTBdNs5GQTFntG7jclk_hDmeQ")  
import time

def get_llm_batch_prediction(df):
    """Send each row (review) to Gemini API for classification (Valid = 0, Invalid = 1)."""
    
    model = genai.GenerativeModel("gemini-1.5-flash")  # Use a faster, cost-efficient model
    ans_dict = {}

    for idx, row in df.iterrows():
        print(idx)
        # Convert row to prompt
        prompt = (
            "Classify this review as valid (0) or invalid (1). "
            "Return only 0 or 1. No extra text. \n\n"
            f"Review: {row.to_dict()}"
        )
        
        try:
            response = model.generate_content(prompt)
            prediction = int(response.text.strip())  # Ensure it's an integer
            ans_dict.update({idx: prediction})
            
        except Exception as e:
            print(f"Error processing row {idx}: {e}")
            ans_dict.update({idx: None})
            
        time.sleep(4.5)  # Avoid hitting API rate limits
    
    return ans_dict  # Return list of predictions


# Apply batch LLM prediction if data_gpt is not empty
if not data_gpt.empty:
    dict = get_llm_batch_prediction(data_gpt)

dict

1
2
4
6
7
9
11
14
15
16
19
20
25
27
29
30
31
32
34
36
38
40
41
46
48
54
60
61
63
64
66
69
71
72
74
75
77
79
80
83
85
87
96
102
116
122
125
126
127
201
203
205
207
208
210
211
217
218
220
221
222
223
224
225
227
229
231
232
233
234
236
237
242
243
251
258
259
264
267
269
270
276
277
279
281
284
292
293
296
299
300
301
304
306
310
311
312
316
317
322
324
325
330
331
332
333
336
338
340
341
344
347
349
350
353
356
361
362
363
364
365
366
369
370
371
373
374
376
377
403

{1: 0,
 2: 0,
 4: 0,
 6: 0,
 7: 0,
 9: 0,
 11: 0,
 14: 0,
 15: 0,
 16: 0,
 19: 0,
 20: 0,
 25: 0,
 27: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 34: 0,
 36: 0,
 38: 0,
 40: 0,
 41: 0,
 46: 0,
 48: 0,
 54: 0,
 60: 0,
 61: 0,
 63: 0,
 64: 0,
 66: 0,
 69: 0,
 71: 0,
 72: 0,
 74: 0,
 75: 0,
 77: 1,
 79: 0,
 80: 0,
 83: 0,
 85: 0,
 87: 0,
 96: 0,
 102: 0,
 116: 0,
 122: 0,
 125: 0,
 126: 0,
 127: 0,
 201: 0,
 203: 0,
 205: 0,
 207: 0,
 208: 0,
 210: 0,
 211: 0,
 217: 0,
 218: 0,
 220: 0,
 221: 0,
 222: 0,
 223: 0,
 224: 1,
 225: 0,
 227: 0,
 229: 0,
 231: 0,
 232: 0,
 233: 0,
 234: 0,
 236: 0,
 237: 0,
 242: 0,
 243: 0,
 251: 0,
 258: 0,
 259: 0,
 264: 0,
 267: 0,
 269: 0,
 270: 0,
 276: 0,
 277: 0,
 279: 0,
 281: 0,
 284: 0,
 292: 0,
 293: 0,
 296: 0,
 299: 0,
 300: 0,
 301: 0,
 304: 0,
 306: 0,
 310: 0,
 311: 0,
 312: 0,
 316: 0,
 317: 0,
 322: 0,
 324: 0,
 325: 0,
 330: 0,
 331: 0,
 332: 0,
 333: 0,
 336: 0,
 338: 0,
 340: 0,
 341: 0,
 344: 0,
 347: 0,
 349: 0,
 350: 0,
 353: 0,
 356: 0,
 361: 0,
 362: 0,
 363: 0,
 364: 0,
 365: 0,
 366: 0,
 369: 0,
 370: 0,
 371: 0,
 373: 0,
 374: 0,
 376: 0,
 377: 0,
 403: 0}

In [58]:
for idx in dict.keys():
    if(dict[idx] != None):
        print(y_submission[idx-1], dict[idx])
        y_submission[idx-1] = dict[idx]

1 0
0 0
1 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
1 0
0 0
1 0
0 0
0 0
0 0
1 0
1 1
0 0
0 0
1 0
0 0
1 0
0 0
0 0
0 0
1 0
0 0
1 0
0 0
1 0
1 0
1 0
0 0
0 0
1 0
1 0
0 0
1 0
0 0
1 0
1 0
1 0
0 1
0 0
0 0
1 0
1 0
0 0
1 0
1 0
1 0
1 0
1 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
1 0
0 0
0 0
0 0
1 0
0 0
0 0
1 0
1 0
0 0
0 0
1 0
1 0
0 0
1 0
0 0
0 0
0 0
1 0
1 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 0
0 0
0 0
0 0

In [59]:
y_submission

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
from collections import Counter

print(Counter(y_submission))

Counter({0: 387, 1: 21})

In [62]:
ans = pd.DataFrame(y_submission, columns=["Quality_Flag"])

In [63]:
ans

     Quality_Flag
0               0
1               0
2               0
3               0
4               0
..            ...
403             0
404             0
405             0
406             0
407             0

[408 rows x 1 columns]

In [64]:
ans.to_csv("final_submission.csv", index = False)